'use strict';

/**
 * Wholesaler B – Mock connector (Home, Lifestyle & Sports)
 *
 * Standard output format:
 * {
 *   source, external_id, name, cost_price, image,
 *   category, stock, created_at, rating, sales,
 *   shipping_time, currency
 * }
 */

const SOURCE = 'wholesaler-b';

const PRODUCTS = [
  {
    external_id: 'wb-001',
    name: 'Odkurzacz Dyson V15',
    cost_price: 2199,
    image: 'https://cdn.qualitet.pl/products/dyson-v15.jpg',
    category: 'sprzet-agd',
    stock: 14,
    created_at: '2024-09-02T09:00:00Z',
    rating: 4.7,
    sales: 77,
    shipping_time: 2,
    currency: 'PLN',
  },
  {
    external_id: 'wb-002',
    name: 'Robot kuchenny Bosch MUM5',
    cost_price: 799,
    image: 'https://cdn.qualitet.pl/products/bosch-mum5.jpg',
    category: 'sprzet-agd',
    stock: 25,
    created_at: '2024-09-08T08:30:00Z',
    rating: 4.2,
    sales: 38,
    shipping_time: 3,
    currency: 'PLN',
  },
  {
    external_id: 'wb-003',
    name: 'Ekspres do kawy DeLonghi',
    cost_price: 999,
    image: 'https://cdn.qualitet.pl/products/delonghi-expresso.jpg',
    category: 'sprzet-agd',
    stock: 18,
    created_at: '2024-09-12T12:00:00Z',
    rating: 4.5,
    sales: 55,
    shipping_time: 2,
    currency: 'PLN',
  },
  {
    external_id: 'wb-004',
    name: 'Rower górski Merida Big Nine',
    cost_price: 2299,
    image: 'https://cdn.qualitet.pl/products/merida-bignine.jpg',
    category: 'kolarstwo',
    stock: 9,
    created_at: '2024-09-18T10:00:00Z',
    rating: 4.6,
    sales: 35,
    shipping_time: 5,
    currency: 'PLN',
  },
  {
    external_id: 'wb-005',
    name: 'Hantle regulowane Bowflex',
    cost_price: 899,
    image: 'https://cdn.qualitet.pl/products/bowflex-hantle.jpg',
    category: 'sprzet-fitness',
    stock: 30,
    created_at: '2024-09-25T08:00:00Z',
    rating: 4.5,
    sales: 60,
    shipping_time: 3,
    currency: 'PLN',
  },
  {
    external_id: 'wb-006',
    name: 'Zestaw narzędzi Bosch Professional',
    cost_price: 499,
    image: 'https://cdn.qualitet.pl/products/bosch-tools.jpg',
    category: 'narzedzia',
    stock: 40,
    created_at: '2024-10-02T09:30:00Z',
    rating: 4.5,
    sales: 48,
    shipping_time: 2,
    currency: 'PLN',
  },
  {
    external_id: 'wb-007',
    name: 'Namiot turystyczny Coleman',
    cost_price: 699,
    image: 'https://cdn.qualitet.pl/products/coleman-tent.jpg',
    category: 'camping',
    stock: 12,
    created_at: '2024-10-08T09:00:00Z',
    rating: 4.4,
    sales: 22,
    shipping_time: 4,
    currency: 'PLN',
  },
  {
    external_id: 'wb-008',
    name: 'Kurtka zimowa Columbia',
    cost_price: 599,
    image: 'https://cdn.qualitet.pl/products/columbia-jacket.jpg',
    category: 'moda',
    stock: 50,
    created_at: '2024-10-12T11:30:00Z',
    rating: 4.3,
    sales: 18,
    shipping_time: 2,
    currency: 'PLN',
  },
  {
    external_id: 'wb-009',
    name: 'Buty Nike Air Max 270',
    cost_price: 449,
    image: 'https://cdn.qualitet.pl/products/nike-air-max-270.jpg',
    category: 'obuwie',
    stock: 60,
    created_at: '2024-10-18T07:45:00Z',
    rating: 4.3,
    sales: 65,
    shipping_time: 3,
    currency: 'PLN',
  },
  {
    external_id: 'wb-010',
    name: 'Perfumy Chanel No. 5',
    cost_price: 699,
    image: 'https://cdn.qualitet.pl/products/chanel-no5.jpg',
    category: 'perfumy',
    stock: 35,
    created_at: '2024-10-22T11:00:00Z',
    rating: 4.9,
    sales: 150,
    shipping_time: 2,
    currency: 'PLN',
  },
  {
    external_id: 'wb-011',
    name: 'Zestaw LEGO Technic 42143',
    cost_price: 599,
    image: 'https://cdn.qualitet.pl/products/lego-technic.jpg',
    category: 'zabawki',
    stock: 28,
    created_at: '2024-10-28T08:30:00Z',
    rating: 4.8,
    sales: 110,
    shipping_time: 2,
    currency: 'PLN',
  },
  {
    external_id: 'wb-012',
    name: 'Wózek dziecięcy Bugaboo Fox 3',
    cost_price: 3999,
    image: 'https://cdn.qualitet.pl/products/bugaboo-fox3.jpg',
    category: 'produkty-dla-niemowlat',
    stock: 6,
    created_at: '2024-11-05T10:00:00Z',
    rating: 4.7,
    sales: 45,
    shipping_time: 5,
    currency: 'PLN',
  },
  {
    external_id: 'wb-013',
    name: 'Krem przeciwzmarszczkowy La Mer',
    cost_price: 799,
    image: 'https://cdn.qualitet.pl/products/la-mer-cream.jpg',
    category: 'pielegnacja-skory',
    stock: 22,
    created_at: '2024-11-12T14:00:00Z',
    rating: 4.8,
    sales: 90,
    shipping_time: 2,
    currency: 'PLN',
  },
  {
    external_id: 'wb-014',
    name: 'Walizka Samsonite Spinner 75',
    cost_price: 799,
    image: 'https://cdn.qualitet.pl/products/samsonite-spinner.jpg',
    category: 'dodatki',
    stock: 16,
    created_at: '2024-11-18T14:30:00Z',
    rating: 4.6,
    sales: 55,
    shipping_time: 3,
    currency: 'PLN',
  },
  // intentionally invalid products (will be filtered out)
  {
    external_id: 'wb-bad-001',
    name: 'Produkt bez zdjęcia',
    cost_price: 300,
    image: '',
    category: 'inne',
    stock: 10,
    created_at: '2024-11-20T10:00:00Z',
    rating: 4.2,
    sales: 30,
    shipping_time: 2,
    currency: 'PLN',
  },
  {
    external_id: 'wb-bad-002',
    name: 'Produkt bez stanu magazynowego',
    cost_price: 250,
    image: 'https://cdn.qualitet.pl/products/no-stock.jpg',
    category: 'inne',
    stock: 0,
    created_at: '2024-11-20T10:00:00Z',
    rating: 4.3,
    sales: 25,
    shipping_time: 2,
    currency: 'PLN',
  },
];

/**
 * Fetch products from Wholesaler B.
 * MVP: returns static data.  Replace with real HTTP call when available.
 *
 * @returns {Promise<Array>}
 */
async function fetchProducts() {
  return PRODUCTS.map((p) => ({ source: SOURCE, ...p }));
}

module.exports = { SOURCE, fetchProducts, PRODUCTS };
